
### Create a new user
POST http://localhost:4420/account/sign-up
Content-Type: application/json

{
    "email":"johndoe@example.com",
    "password":"1234",
    "firstName":"john",
    "lastName":"doe"
}

### login into an account, **user gets a new api key whenever they login**
POST http://localhost:4420/account/sign-in
Content-Type: application/json

{
    "email":"johndoe@example.com",
    "password":"1234"
}