### get all notes owned by a specific user
GET http://localhost:4420/notes?api_key={API KEY HERE}

### add new note
POST http://localhost:4420/notes/new?api_key={API KEY HERE}
Content-Type: application/json

{
"title":"a new note title ",
"body":"body of a new note"
}

### edit a note
PUT http://localhost:4420/notes/edit/{ NOTE ID }?api_key={API KEY HERE }
Content-Type: application/json

{
    "title":"an updated title",
    "body":"an updated body"
}

### move a note to trash, **this doesn't permanently delete the note**
PUT http://localhost:4420/notes/toTrash/{NOTE ID }?api_key={API KEY HERE }

### remove a note out from trash,
PUT http://localhost:4420/notes/outOfTrash/{NOTE ID }?api_key={API KEY HERE }